//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Receiver.EncodeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EncodeService.IEncodeService")]
    public interface IEncodeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncodeService/Encode", ReplyAction="http://tempuri.org/IEncodeService/EncodeResponse")]
        Entities.Drop Encode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncodeService/GetNumberOfBlocks", ReplyAction="http://tempuri.org/IEncodeService/GetNumberOfBlocksResponse")]
        int GetNumberOfBlocks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncodeService/GetChunkSize", ReplyAction="http://tempuri.org/IEncodeService/GetChunkSizeResponse")]
        int GetChunkSize();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncodeService/GetFileSize", ReplyAction="http://tempuri.org/IEncodeService/GetFileSizeResponse")]
        int GetFileSize();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEncodeServiceChannel : Client.Receiver.EncodeService.IEncodeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EncodeServiceClient : System.ServiceModel.ClientBase<Client.Receiver.EncodeService.IEncodeService>, Client.Receiver.EncodeService.IEncodeService {
        
        public EncodeServiceClient() {
        }
        
        public EncodeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EncodeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EncodeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EncodeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entities.Drop Encode() {
            return base.Channel.Encode();
        }
        
        public int GetNumberOfBlocks() {
            return base.Channel.GetNumberOfBlocks();
        }
        
        public int GetChunkSize() {
            return base.Channel.GetChunkSize();
        }
        
        public int GetFileSize() {
            return base.Channel.GetFileSize();
        }
    }
}
